#!/usr/bin/env sh

# Configure git defaults
git config --global user.name "jovyan"
git config --global user.email "jovyan@mybinder"

# Install packages and enable TypeScript
npm install
npm link tslab
tslab install
